; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lilygo-t-display-s3]
platform = espressif32
board = lilygo-t-display-s3
framework = arduino
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit MPU6050@^2.2.6
	adafruit/Adafruit BMP085 Library@^1.2.4
	me-no-dev/ESPAsyncWebServer@^3.6.0
	bblanchon/ArduinoJson@^7.3.1
	me-no-dev/AsyncTCP@^3.3.2
board_build.embed_txtfiles = 
	data/index.html
	data/style.css
	data/script.js
board_build.embed_files = 
	data/Z-Craft_color_invert_trans.png